### ISSUE TITLE
Using pocket-ic-rs goes err

### ISSUE THREAD

**Issue by q2333gh** [dfinity/pocketic#2]
I have downlaod pocket-ic v2.0.1
I have config POCKET_IC_BIN in linux env 
and 
```rust
// this code goes err
  let mut replica = PocketIcBuilder::new()
    .with_nns_subnet()
    .with_application_subnet()
    .build();

```
```
// Err here:
running 1 test
test backend_test::nns_wallet_test::create_a_nns_wallet has been running for over 60 seconds
2023-11-28T11:26:54.383046Z  INFO pocket_ic_server: The PocketIC server is listening on port 36587
thread 'backend_test::nns_wallet_test::create_a_nns_wallet' panicked at /home/btwl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pocket-ic-2.0.1/src/lib.rs:183:14:
Could not parse response for create instance request: reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::expect
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1034:23
   4: pocket_ic::PocketIc::from_config
             at /home/btwl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pocket-ic-2.0.1/src/lib.rs:177:45

running 1 test
2023-11-28T11:28:05.774075Z  INFO pocket_ic_server: The PocketIC server is listening on port 44779
thread 'backend_test::nns_wallet_test::create_a_nns_wallet' panicked at /home/btwl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pocket-ic-2.0.1/src/lib.rs:183:14:
Could not parse response for create instance request: reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) }
stack backtrace:

running 1 test
2023-11-28T11:36:23.677311Z  INFO pocket_ic_server: The PocketIC server is listening on port 33855
thread 'backend_test::nns_wallet_test::create_a_nns_wallet' panicked at /home/btwl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pocket-ic-2.0.1/src/lib.rs:183:14:
Could not parse response for create instance request: reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::expect
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1034:23
   4: pocket_ic::PocketIc::from_config
             at /home/btwl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pocket-ic-2.0.1/src/lib.rs:177:45
   5: pocket_ic::PocketIcBuilder::build
             at /home/btwl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pocket-ic-2.0.1/src/lib.rs:84:9
   6: integration_tests::client::setup::setup_new_env
             at ./backend/integration_tests/src/client/setup.rs:29:21
   7: integration_tests::backend_test::nns_wallet_test::create_a_nns_wallet
             at ./backend/integration_tests/src/backend_test/nns_wallet_test.rs:6:3
   8: integration_tests::backend_test::nns_wallet_test::create_a_nns_wallet::{{closure}}
             at ./backend/integration_tests/src/backend_test/nns_wallet_test.rs:4:30
   9: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test backend_test::nns_wallet_test::create_a_nns_wallet ... FAILED

failures:

failures:
    backend_test::nns_wallet_test::create_a_nns_wallet

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 39.98s

```

**Comment by fxgst** [comment]
Hi @q2333gh, this looks like a version mismatch to me.
Could you please double check that you do not have an older version than PocketIC 2.0.1 in your current directory from where you execute the test and that `POCKET_IC_BIN` points to the 2.0.1 version of the server?

**Comment by q2333gh** [comment]
> Hi @q2333gh, this looks like a version mismatch to me. Could you please double check that you do not have an older version than PocketIC 2.0.1 in your current directory from where you execute the test and that `POCKET_IC_BIN` points to the 2.0.1 version of the server?

here is my code lib ref and local pocket-ic bin :
```toml
pocket-ic = "2.0.1"
```
```bash
> pocket-ic --version
pocket-ic-server 2.0.1
> whereis pocket-ic
pocket-ic: /usr/bin/pocket-ic
>echo $POCKET_IC_BIN
/opt/pocket-ic
>/opt/pocket-ic --version
pocket-ic-server 1.0.0
> cp ~/app/pocket-ic  /opt/
> /opt/pocket-ic --version
pocket-ic-server 2.0.1
```
ohh yes. i have used old version of pocket-ic binary.
and it still goes err when a run again after update pocket-ic 
![image](https://github.com/dfinity/pocketic/assets/32679742/ae9bdafa-49e4-41ed-8788-c9bd794ea4ee)
almost the same err .

**Comment by fxgst** [comment]
Hi @q2333gh, thanks for following up.
If the code crashes with "Could not parse response for create instance request", this is likely another version mismatch. 
But since you've already double checked the versions, let's try this:

Create a new test where you just call `let pic = PocketIc::new();`, and execute this test only. Make sure that you've downloaded the latest binary (2.0.1) with the latest library (2.0.1). Please put the binary in your current working directory, or call the test like `POCKET_IC_BIN=/some/absolute/path/to/pic/2.0.1 cargo test <your_test>`.
Please let me know if you have further issues.

**Comment by q2333gh** [comment]
> Hi @q2333gh, thanks for following up. If the code crashes with "Could not parse response for create instance request", this is likely another version mismatch. But since you've already double checked the versions, let's try this:
> 
> Create a new test where you just call `let pic = PocketIc::new();`, and execute this test only. Make sure that you've downloaded the latest binary (2.0.1) with the latest library (2.0.1). Please put the binary in your current working directory, or call the test like `POCKET_IC_BIN=/some/absolute/path/to/pic/2.0.1 cargo test <your_test>`. Please let me know if you have further issues.
I create a  fresh new docker ubuntu container to run this code :
```rust
use chrono::format::strftime::StrftimeItems;
use chrono::{DateTime, Utc};
use pocket_ic::*;
use std::time::SystemTime;
fn main() {
  println!("Hello, world!");
  let pic = PocketIc::new();
  let t: SystemTime = pic.get_time();
  let datetime: DateTime<Utc> = t.into();

  println!("{}", datetime.to_string());
}
output goes seemly goes all right:
```
root@c6a2b1c712af ~/code# ./test1
Hello, world!
2023-12-01T08:59:34.708794Z  INFO pocket_ic_server: The PocketIC server is listening on port 40843
2021-05-06 19:17:10 UTC
root@c6a2b1c712af ~/code# 2023-12-01T09:05:35.192671Z  INFO pocket_ic_server: The PocketIC server will terminate
root@c6a2b1c712af ~/code# ls
pocket-ic  test1
root@c6a2b1c712af ~/code# ./pocket-ic --version
pocket-ic-server 2.0.1
```

but host machine still goes same err before .

**Comment by q2333gh** [comment]
> How and to what value did you set `POCKET_IC_BIN` on the host machine? Is it pointing to the correct binary?
I try to use no POCKET_IC_BIN
here`s the code:
```rust
use chrono::format::strftime::StrftimeItems;
use chrono::{DateTime, Utc};
use pocket_ic::*;
use std::time::SystemTime;
fn main() {
  // println!("Hello, world!");
  let pic = PocketIc::new();
  let t: SystemTime = pic.get_time();
  let datetime: DateTime<Utc> = t.into();

  println!("{}", datetime.to_string());
}
```
i compile and copy the binary file to a docker-ubuntu-container vm . it works perfect. correctly print time and exit .
but on my host machine exec it . it firstly show EOF err at we disscus before.
So I tried to disable proxy using `export https_proxy=` `export http_proxy=` and then err become to this : 
(For the reason why i disable the proxy is i used to use `bear` cmd with C code stuff. somehow disable proxy that `bear --  make `cmd works~ hah.)

```log
thread 'main' panicked at /home/btwl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pocket-ic-2.0.1/src/lib.rs:183:14:
Failed to get result: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(33813), path: "/instances", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }
stack backtrace:
   0:     0x55d3f2fcbeac - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55d3f2fcbeac - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d3f2fcbeac - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d3f2fcbeac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55d3f2ff932c - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x55d3f2ff932c - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x55d3f2fc895e - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x55d3f2fcbc94 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55d3f2fcbc94 - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55d3f2fcd583 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x55d3f2fcd29c - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0x55d3f2fcdb09 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:     0x55d3f2fcda07 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
  13:     0x55d3f2fcc3d6 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55d3f2fcd752 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:     0x55d3f2601c43 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0x55d3f260213a - core::result::unwrap_failed::hccb456d39e9c31fc
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
  17:     0x55d3f260faef - core::result::Result<T,E>::expect::hca7c141f5e9a89c7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1034:23
  18:     0x55d3f2603505 - pocket_ic::PocketIc::from_config::h66e68cf41b98632a
                               at /home/btwl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pocket-ic-2.0.1/src/lib.rs:179:45
  19:     0x55d3f26031f1 - pocket_ic::PocketIcBuilder::build::he29569587ff216ba
                               at /home/btwl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pocket-ic-2.0.1/src/lib.rs:84:9
  20:     0x55d3f2603309 - pocket_ic::PocketIc::new::h6bafb85b72b5ec68
                               at /home/btwl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pocket-ic-2.0.1/src/lib.rs:164:9
  21:     0x55d3f2602bba - pic_test::main::hb7456b763d0615b5
                               at /home/btwl/Desktop/ic/tax_lint/backend/ohter_test/pic_test/src/main.rs:7:13
  22:     0x55d3f26024eb - core::ops::function::FnOnce::call_once::h93218655e83439ee
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  23:     0x55d3f26027de - std::sys_common::backtrace::__rust_begin_short_backtrace::hf06afc02e5dd7f69
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:154:18
  24:     0x55d3f2602dd1 - std::rt::lang_start::{{closure}}::hc89a581580d5f47a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:166:18
  25:     0x55d3f2fc3c1b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbcc4f8a3f5ada78c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
  26:     0x55d3f2fc3c1b - std::panicking::try::do_call::he5f117a9e13dadde
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  27:     0x55d3f2fc3c1b - std::panicking::try::h2f3af9afce3a0443
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  28:     0x55d3f2fc3c1b - std::panic::catch_unwind::h6d6c387f38ef05ea
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  29:     0x55d3f2fc3c1b - std::rt::lang_start_internal::{{closure}}::h6ca09d5905711415
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
  30:     0x55d3f2fc3c1b - std::panicking::try::do_call::ha9fd18ea06654a4b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  31:     0x55d3f2fc3c1b - std::panicking::try::hda5c2a4432362341
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  32:     0x55d3f2fc3c1b - std::panic::catch_unwind::h440f731b142bc235
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  33:     0x55d3f2fc3c1b - std::rt::lang_start_internal::hc0b4e50f058f62ce
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
  34:     0x55d3f2602daa - std::rt::lang_start::hbcee5ac85511efb1
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:165:17
  35:     0x55d3f2602d6e - main
  36:     0x7f645a829d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  37:     0x7f645a829e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  38:     0x55d3f26023f5 - _start
  39:                0x0 - <unknown>

```

**Comment by q2333gh** [comment]
It just suddenly worked. can figure out why ...
```bash
btwl@btwl-virtual-machine ~/D/i/t/b/o/pic_test (master) [101]> export https_proxy=
btwl@btwl-virtual-machine ~/D/i/t/b/o/pic_test (master)> export http_proxy=
btwl@btwl-virtual-machine ~/D/i/t/b/o/pic_test (master)> ./pic_test
2021-05-06 19:17:10 UTC
btwl@btwl-virtual-machine ~/D/i/t/b/o/pic_test (master)> ./pic_test
2021-05-06 19:17:10 UTC
btwl@btwl-virtual-machine ~/D/i/t/b/o/pic_test (master)> ./pic_test
2021-05-06 19:17:10 UTC
```
